### ISSUE TITLE
Should be a hyphen

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#14]
Check to see if micro-retail is a hyphen. 
<img width="979" alt="Screen Shot 2019-12-09 at 10 55 00 AM" src="https://user-images.githubusercontent.com/25647624/70450817-60273e80-1a72-11ea-8d77-7d42e614dfc0.png">

**Comment by andrewmarino** [comment]
This is currently using a hyphen. Closing for now!
