### ISSUE TITLE
H2 size for mobile

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#17]
iPhone 8, Safari.
I think we should reduce or tighten H2, thoughts? 

![7F22570F-6861-4517-8F74-8275DEB22689_1_105_c](https://user-images.githubusercontent.com/25647624/70458338-ded6a880-1a7f-11ea-84d7-08c0773d7ba9.jpeg)

**Comment by andrewmarino** [comment]
Agreed—this is actually a network wide fix that I'll want to implement across RTP sites.
