### ISSUE TITLE
Show frontier image before icon content

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#18]
iPhone 8, Safari.
Show frontier full-width photo before icons.
![7CD67294-80A7-4231-95AA-7AC6A7F7CD81_1_105_c](https://user-images.githubusercontent.com/25647624/70458540-3e34b880-1a80-11ea-988f-0cab1938509b.jpeg)

**Comment by andrewmarino** [comment]
Good idea! I think what we can do here is set up a hidden element before this section with just the image and then only show it on mobile. Will follow up once it's ready.

**Comment by andrewmarino** [comment]
Fixed!
