### ISSUE TITLE
Boxyard icon sizes for mobile. 

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#20]
iPhone 8, Safari.
Can we enlarge the logos in the mobile view?

![7F6933B9-1420-4A72-BF37-BCE9B4C4DF88_1_105_c](https://user-images.githubusercontent.com/25647624/70458749-c0bd7800-1a80-11ea-8bb8-6783eeb1d9d1.jpeg)

**Comment by andrewmarino** [comment]
Fixed!
