### ISSUE TITLE
STEM section

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#21]
iPhone 8, Safari.
Let's look at adding blue over the entire image similar to the partnerships section. 

![17BBF70F-D197-4F01-B73E-121648B76F90_1_105_c](https://user-images.githubusercontent.com/25647624/70459671-abe1e400-1a82-11ea-8b6e-7eaa7da09604.jpeg)

**Comment by andrewmarino** [comment]
Fixed!
