### ISSUE TITLE
Common page margin

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#22]
iPhone 8, Safari.
Can we create a common page margin on the mobile view?

![2FCDD550-DA8C-4894-8E45-7DC4E1939847_1_105_c](https://user-images.githubusercontent.com/25647624/70459835-05e2a980-1a83-11ea-936f-b37dcdbe4bea.jpeg)

**Comment by andrewmarino** [comment]
Yep, this section is Beaver Builder and was missing some mobile padding. Thanks!
