### ISSUE TITLE
Apostrophe in the Park’s.

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#23]
Can you change the apostrophe in the word Park’s to a smart apostrophe?

<img width="978" alt="Screen Shot 2019-12-10 at 8 51 08 AM" src="https://user-images.githubusercontent.com/25647624/70535091-6c6ed280-1b2a-11ea-8b44-3feef26fd274.png">

**Comment by andrewmarino** [comment]
Sure can! This is now fixed.
