### ISSUE TITLE
Press releases need live links

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/rtp#25]
We need to get and add links to the relevant press releases for the following:

- LabCorp (also capitalize their name properly in the card title)
- Credit Suisse
- G1 Therapeutics
- Alexandria Center
- Rho
- Duke Health Tech
- Redevelopment Partnerships

Vestaron is linked to WRAL, but we need a little blurb.

Additionally, make sure all links open in a new tab.

**Comment by andrewmarino** [comment]
I've requested all this info from the client twice last week and have not received a response. Will follow up again!

**Comment by andrewmarino** [comment]
@isabisa on an unrelated note, I had to update some settings on the link field for custom figure card BB module to allow external links but am running into a weird problem.

https://kb.wpbeaverbuilder.com/article/616-cmdg-10-setting-fields-reference#link-field

The checkboxes settings do render but our RTP Core theme / Materialize styles are overriding the checkboxes and rendering them useless. Any ideas on how to get around this? I haven't pushed the code yet but can if we can troubleshoot it further.

Should look like this....
https://d33v4339jhl8k0.cloudfront.net/docs/assets/574cac7bc6979138ff609a9e/images/5bdc8dea04286356f0a5627b/file-kItrMphYe8.png

but it looks like this....
![Screen Shot 2019-12-16 at 3 11 00 PM](https://user-images.githubusercontent.com/6686529/70939453-4c517e80-2016-11ea-8c54-12c955c04907.png)
