### ISSUE TITLE
Video style

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#6]
Remove Black rule above video frame. Mac OS, 15"laptop, Chrome Browser 
<img width="738" alt="Screen Shot 2019-12-09 at 9 36 33 AM" src="https://user-images.githubusercontent.com/25647624/70447470-c14c1380-1a6c-11ea-8a15-1341d53203eb.png">

**Comment by andrewmarino** [comment]
I believe this is fixed now in 2abc0c0ecfde480c7bbd2adb69a2bc52175d155d.
