### ISSUE TITLE
Boxyard logo sizes

### ISSUE THREAD

**Issue by budnorthern** [unitymakesus/rtp#7]
Update logo artwork. Add coming soon artwork. Mac OS, 15" laptop, Chrome browser.
<img width="739" alt="Screen Shot 2019-12-09 at 10 17 59 AM" src="https://user-images.githubusercontent.com/25647624/70447774-50f1c200-1a6d-11ea-85dd-063d2492ea1b.png">

**Comment by andrewmarino** [comment]
👍
